name: New content or feature suggestion
description: Proposals for new content or features on MDN Web Docs
title: Enter your proposal here
labels: ["proposal", "needs triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to put together a proposal for adding/updating content or a website feature on MDN Web Docs. We have a well-defined process for handling these requests which you can read about in our [Community Guidelines](https://developer.mozilla.org/en-US/docs/MDN/Community).

        New or experimental web platform features must be supported in at least **one stable browser release** before documentation is published to MDN. For more information, see the [What we write](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/What_we_write#suggesting_content) and the [experimental technologies](https://developer.mozilla.org/en-US/docs/MDN/Writing_guidelines/Experimental_deprecated_obsolete) documentation.
  - type: textarea
    attributes:
      label: Proposal
      description: Please describe the content or feature you are proposing and why it is needed.
    validations:
      required: true
  - type: dropdown
    id: browser
    attributes:
      label: Browser support
      description: Is this feature available in a stable browser release?
      multiple: true
      options:
        - Firefox
        - Chrome
        - Safari
  - type: textarea
    id: task-list
    attributes:
      label: Tasks
      description: What needs to be done to complete this task?
      value: |
        - [ ]
  - type: textarea
    attributes:
      label: Dependencies
      description: |
        Does this task depend on anything else to be completed first? Links to GitHub issues or pull requests are helpful.
      value: |
        - [ ]
  - type: textarea
    attributes:
      label: Additional information
      description: |
        Please add any additional information to support this proposal (screenshots, specification links, browser implementation bugs etc...)
  - type: input
    attributes:
      label: Are you willing to support this work?
      description: >
        MDN Web Docs is an open source project and welcomes contributions.
        Let us know whether you are willing to help with the proposed work and in what capacity; this can be undertaking the task itself or supporting with reviews and/or feedback.
