name: Nominate a maintainer
description: Use this template when nominating an individual to become a maintainer of an MDN Web Docs repository.
title: Nominating a maintainer for [repository-name]
labels: ["repo maintainer nomination"]
assignees:
  - schalkneethling
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to nominate an individual to become a co-maintainer.
        Please ensure that you have read and understood the responsibilities of [a volunteer maintainer](https://developer.mozilla.org/en-US/docs/MDN/Community/Pull_requests) before continuing.
  - type: input
    attributes:
      label: Given name or GitHub username
    validations:
      required: true
  - type: input
    attributes:
      label: GitHub profile link
      placeholder: https://github.com/<username>
    validations:
      required: true
  - type: input
    attributes:
      label: Repository URL
      description: The URL of the repository this person will co-maintain.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why are you nominating this person?
      description: Tell us why you are nominating this person to become a co-maintainer of the repository.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Supporting evidence
      description: |
        Provide evidence to support your nomination such as contributions and interactions with the community.
          Links to [commit logs](https://github.com/mdn/yari/commits?author=schalkneethling) in a repository are also appropriate.
    validations:
      required: true
