name: Nominate a spotlight contributor
description: Use this template when nominating aspotlight contributor.
title: Nominating [GitHub username] as a spotlight contributor
labels: ["spotlight-contributor"]
assignees:
  - schalkneethling
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to nominate an individual to be features as a [spotlight contributor](https://github.com/mdn/mdn-contributor-spotlight). Thank you for taking the time to nominate an individual to be featured as a spotlight contributor. Please read our [short guide on the prerequisites](https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams#spotlight-contributor) when nominating a spotlight contributor.
  - type: input
    attributes:
      label: Given name or GitHub username
    validations:
      required: true
  - type: input
    attributes:
      label: GitHub profile link
      placeholder: https://github.com/<username>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why are you nominating this individual?
      description: Please provide a short description of why you are nominating this individual to become an spotlight contributor.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Supporting evidence
      description: Evidence to support the nomination. For example links to contributions as well as interactions with the larger community. For example a link to a [commit log](https://github.com/mdn/yari/commits?author=schalkneethling) on a repository.
    validations:
      required: true
