name: Nominate an invited expert
description: Use this template when nominating an invited expert.
title: Nominating an invited expert for [technology topic]
labels: ["invited-expert-nomination"]
assignees:
  - schalkneethling
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to nominate an invited expert.
        Make sure that you have read and understood the [responsibilities of an invited expert](https://developer.mozilla.org/en-US/docs/MDN/Community/Users_teams#invited_experts_program) before submitting a nomination.
  - type: input
    attributes:
      label: Given name or GitHub username
    validations:
      required: true
  - type: input
    attributes:
      label: GitHub profile link
      placeholder: https://github.com/<username>
    validations:
      required: true
  - type: textarea
    attributes:
      label: Why are you nominating this person?
      description: Tell us why you are nominating this person to become an invited expert.
    validations:
      required: true
  - type: textarea
    attributes:
      label: Supporting evidence
      description: |
        Provide evidence to support your nomination such as contributions and interactions with the community.
        Links to [commit logs](https://github.com/mdn/yari/commits?author=schalkneethling) in a repository are also appropriate.
    validations:
      required: true
